### ISSUE TITLE
source font appears to be nonfree

### ISSUE THREAD

**Issue by Moth-Tolias** [patchstep/Pixelary#1]
hi, it looks like [paskowy](https://www.dafont.com/paskowy.font) is licensed for "personal use only"? if that's the case and pixelary is based on it, i'm not sure it's legal to re-license this font under MIT.

**Comment by mia-riezebos** [comment]
I understand the concerns. 
I did not use Paskowy binaries or distributables in any part of Pixelary's source. It was only used for reference. This by itself is not enough to dispute copyright infringement, but I did do more to warrant fair use. 

I altered a considerable number of glyphs, both to improve legibility and compatibility with Pixelary's monospace nature. 
I also do not believe the (letter) glyphs to be unique / complex enough to be a copyright concern. I'm fairly confident there are too many fonts already out there with similar or identical glyphs that paskowy cannot claim them as copyrighted material.

As for the binary stripes, in Paskowy, the stripes are arbitrary, without meaning. The stripes in Pixelary being binary representations of the characters is conceptually *based* on the look of Paskowy, but transformative.

Fair use is a gray area, and if the author of Paskowy takes issue with my arguments of fair use, I am open to discussing other possibilities, such as sub-licensing, or altering it further.

Apologies for the late reply. Life's a bitch and things slip under the radar.

**Comment by mia-riezebos** [comment]
As a follow-up note, in the README.md I specify that both Paskowy and Pixelary are free for personal and (explicitly stated) commercial use. I can't find where I found this information but I wouldn't state this so explicitly if I didn't read this somewhere on an authoritative source.

I will conduct some further research. It would be a pity if the license has changed, though it still would not impact Pixelary's MIT nature per say.
